version: "2.1"

services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports: ["8000:8080"]
    stop_grace_period: 1m30s
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    restart: unless-stopped

  rabbitmq:
    build: ./rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]
    restart: unless-stopped

  spring-cloud-stream-app:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ./docker/spring-cloud-stream-app/Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes: ["spring-cloud-stream-app-data:/opt/app"]
    ports: ["8080:8080"]
    networks: [backing-services]
    restart: unless-stopped

volumes:
  rabbitmq-data: {}
  spring-cloud-stream-app-data: {}

networks:
  backing-services:
    driver: bridge
